In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from pprint import pprint
import requests
import statistics
import time
import quandl  #Used for data import
quandl.ApiConfig.api_key = 'vxSYNGB-9owcVsRx_SEF'
pd.set_option('display.max_colwidth', None)

In [2]:
zillow_reg=quandl.get_table('ZILLOW/DATA', region_id='102001',paginate=True)
zillow_reg

      indicator_id region_id       date        value
None
0             ZSFH    102001 2021-04-30  280803.0000
1             ZSFH    102001 2021-03-31  277043.0000
2             ZSFH    102001 2021-02-28  273699.0000
3             ZSFH    102001 2021-01-31  269769.0000
4             ZSFH    102001 2020-12-31  265679.0000
...            ...       ...        ...          ...
11477         CRAM    102001 2018-08-31       0.1768
11478         CRAM    102001 2018-07-31       0.1704
11479         CRAM    102001 2018-06-30       0.1556
11480         CRAM    102001 2018-05-31       0.1476
11481         CRAM    102001 2018-04-30       0.1316

[11482 rows x 4 columns]

In [8]:
zillow_reg[zillow_reg['indicator_id']=='ZATT']

     indicator_id region_id       date     value
None
608          ZATT    102001 2021-04-30  555747.0
609          ZATT    102001 2021-03-31  548297.0
610          ZATT    102001 2021-02-28  541849.0
611          ZATT    102001 2021-01-31  534166.0
612          ZATT    102001 2020-12-31  526592.0
...           ...       ...        ...       ...
907          ZATT    102001 1996-05-31  204171.0
908          ZATT    102001 1996-04-30  204076.0
909          ZATT    102001 1996-03-31  204038.0
910          ZATT    102001 1996-02-29  204032.0
911          ZATT    102001 1996-01-31  204091.0

[304 rows x 4 columns]

In [10]:
zillow_reg['indicator_id'].value_counts()

SRSW    675
SSSW    675
SASW    675
SRAW    675
SAAW    675
SSAW    675
Z1BR    304
ZABT    304
ZSFH    304
Z3BR    304
ZATT    304
Z2BR    304
ZCON    304
ZALL    304
Z5BR    304
Z4BR    304
LRSW    175
IRAW    175
ISSW    175
LSSW    175
LRAW    175
LSAW    175
IRSW    175
ISAW    175
CSAW    163
CSSW    163
SRAM    158
SASM    158
SAAM    158
SRSM    158
SSAM    158
SSSM    158
MRAW    150
CRAW    150
MSAW    150
NRAW    150
CRSW    150
NSAW    150
RSSA     88
RSNA     88
ISSM     43
LSAM     43
LRAM     43
IRSM     43
IRAM     43
LRSM     43
ISAM     43
LSSM     43
CSAM     40
CSSM     40
CRSM     37
CRAM     37
NSAM     36
MRAM     36
MSAM     36
NRAM     36
Name: indicator_id, dtype: int64

In [4]:
zillow_reg.dtypes

indicator_id            object
region_id               object
date            datetime64[ns]
value                  float64
dtype: object

In [6]:
zillow_reg['region_id'].unique()

array(['102001'], dtype=object)

In [3]:
zillow_reg['indicator_id'].unique()

array(['ZSFH', 'ZCON', 'ZATT', 'ZALL', 'ZABT', 'Z5BR', 'Z4BR', 'Z3BR',
       'Z2BR', 'Z1BR', 'SSSW', 'SSSM', 'SSAW', 'SSAM', 'SRSW', 'SRSM',
       'SRAW', 'SRAM', 'SASW', 'SASM', 'SAAW', 'SAAM', 'RSSA', 'RSNA',
       'NSAW', 'NSAM', 'NRAW', 'NRAM', 'MSAW', 'MSAM', 'MRAW', 'MRAM',
       'LSSW', 'LSSM', 'LSAW', 'LSAM', 'LRSW', 'LRSM', 'LRAW', 'LRAM',
       'ISSW', 'ISSM', 'ISAW', 'ISAM', 'IRSW', 'IRSM', 'IRAW', 'IRAM',
       'CSSW', 'CSSM', 'CSAW', 'CSAM', 'CRSW', 'CRSM', 'CRAW', 'CRAM'],
      dtype=object)

In [4]:
zillow_ind=quandl.get_table('ZILLOW/INDICATORS',paginate=True)
zillow_ind

,indicator_id,indicator,category
None,,,
0,ZSFH,ZHVI Single-Family Homes Time Series ($),Home values
1,ZCON,ZHVI Condo/Co-op Time Series ($),Home values
2,ZATT,ZHVI All Homes- Top Tier Time Series ($),Home values
3,ZALL,"ZHVI All Homes (SFR, Condo/Co-op) Time Series ($)",Home values
4,ZABT,ZHVI All Homes- Bottom Tier Time Series ($),Home values
5,Z5BR,ZHVI 5+ Bedroom Time Series ($),Home values
6,Z4BR,ZHVI 4-Bedroom Time Series ($),Home values
7,Z3BR,ZHVI 3-Bedroom Time Series ($),Home values
8,Z2BR,ZHVI 2-Bedroom Time Series ($),Home values
9,Z1BR,ZHVI 1-Bedroom Time Series ($),Home values
10,SSSW,"Median Sale Price (Smooth, SFR only, Weekly View)",Inventory and sales
11,SSSM,"Median Sale Price (Smooth, SFR only, Monthly)",Inventory and sales
12,SSAW,"Median Sale Price (Smooth, All Homes, Weekly View)",Inventory and sales
13,SSAM,"Median Sale Price (Smooth, All Homes, Monthly)",Inventory and sales
14,SRSW,"Median Sale Price (Raw, SFR only, Weekly View)",Inventory and sales
15,SRSM,"Median Sale Price (Raw, SFR only, Monthly)",Inventory and sales
16,SRAW,"Median Sale Price (Raw, All Homes, Weekly View)",Inventory and sales
17,SRAM,"Median Sale Price (Raw, All Homes, Monthly)",Inventory and sales
18,SASW,"Median Sale Price (Smooth & Seasonally Adjusted, SFR only, Weekly View)",Inventory and sales
19,SASM,"Median Sale Price (Smooth & Seasonally Adjusted, SFR only, Monthly)",Inventory and sales
20,SAAW,"Median Sale Price (Smooth & Seasonally Adjusted, All Homes, Weekly View)",Inventory and sales
21,SAAM,"Median Sale Price (Smooth & Seasonally Adjusted, All Homes, Monthly)",Inventory and sales
22,RSSA,"ZORI (Smoothed, Seasonally Adjusted): All Homes Plus Multifamily Time Series ($)",Rentals
23,RSNA,ZORI (Smoothed): All Homes Plus Multifamily Time Series ($),Rentals
24,NSAW,"Median Days to Pending (Smooth, All Homes, Weekly View)",Inventory and sales
25,NSAM,"Median Days to Pending (Smooth, All Homes, Monthly)",Inventory and sales
26,NRAW,"Median Days to Pending (Raw, All Homes, Weekly View)",Inventory and sales
27,NRAM,"Median Days to Pending (Raw, All Homes, Monthly)",Inventory and sales
28,MSAW,"Mean Days to Pending (Smooth, All Homes, Weekly View)",Inventory and sales
29,MSAM,"Mean Days to Pending (Smooth, All Homes, Monthly)",Inventory and sales
30,MRAW,"Mean Days to Pending (Raw, All Homes, Weekly View)",Inventory and sales
31,MRAM,"Mean Days to Pending (Raw, All Homes, Monthly)",Inventory and sales
32,LSSW,"Median List Price (Smooth, SFR Only, Weekly View)",Inventory and sales
33,LSSM,"Median List Price (Smooth, SFR Only, Monthly)",Inventory and sales
34,LSAW,"Median List Price (Smooth, All Homes, Weekly View)",Inventory and sales
35,LSAM,"Median List Price (Smooth, All Homes, Monthly)",Inventory and sales
36,LRSW,"Median List Price (Raw, SFR Only, Weekly View)",Inventory and sales
37,LRSM,"Median List Price (Raw, SFR Only, Monthly)",Inventory and sales
38,LRAW,"Median List Price (Raw, All Homes, Weekly View)",Inventory and sales
39,LRAM,"Median List Price (Raw, All Homes, Monthly)",Inventory and sales
40,ISSW,"For-Sale Inventory (Smooth, SFR only, Weekly View)",Inventory and sales
41,ISSM,"For-Sale Inventory (Smooth, SFR only, Monthly)",Inventory and sales
42,ISAW,"For-Sale Inventory (Smooth, All Homes, Weekly View)",Inventory and sales
43,ISAM,"For-Sale Inventory (Smooth, All Homes, Monthly)",Inventory and sales
44,IRSW,"For-sale Inventory (Raw, SFR only, Weekly View)",Inventory and sales
45,IRSM,"For-sale Inventory (Raw, SFR only, Monthly)",Inventory and sales
46,IRAW,"For-Sale Inventory (Raw, All Homes, Weekly View)",Inventory and sales
47,IRAM,"For-Sale Inventory (Raw, All Homes, Monthly)",Inventory and sales
48,CSSW,"Share of Listings With a Price Cut (Smooth, SFR Only, Weekly View)",Inventory and sales
49,CSSM,"Share of Listings With a Price Cut (Smooth, SFR Only, Monthly)",Inventory and sales
50,CSAW,"Share of Listings With a Price Cut (Smooth, All Homes, Weekly View)",Inventory and sales
51,CSAM,"Share of Listings With a Price Cut (Smooth, All Homes, Monthly)",Inventory and sales
52,CRSW,"Share of Listings With a Price Cut (Raw, SFR Only, Weekly View)",Inventory and sales
53,CRSM,"Share of Listings With a Price Cut (Raw, SFR Only, Monthly)",Inventory and sales
54,CRAW,"Share of Listings With a Price Cut (Raw, All Homes, Weekly View)",Inventory and sales
55,CRAM,"Share of Listings With a Price Cut (Raw, All Homes, Monthly)",Inventory and sales

In [ ]:
y=quandl.get_table('ZILLOW/',indicator_id='CRAM',paginate=True)
y

In [114]:
pd.set_option('display.max_colwidth', None)

### Region table:

In [5]:
zillow_regions=quandl.get_table('ZILLOW/REGIONS',paginate=True)
zillow_regions

      region_id region_type                                           region
None
0         99999         zip   98847; WA; Wenatchee; Chelan County; Peshastin
1         99998         zip              98846; WA; Okanogan County; Pateros
2         99997         zip  98845; WA; Wenatchee; Douglas County; Palisades
3         99996         zip             98844; WA; Okanogan County; Oroville
4         99995         zip     98843; WA; Wenatchee; Douglas County; Orondo
...         ...         ...                                              ...
79169    100000         zip      98848; WA; Moses Lake; Grant County; Quincy
79170     10000        city                  Bloomington; MD; Garrett County
79171      1000      county                      Echols County; GA; Valdosta
79172       100      county               Bibb County; AL; Birmingham-Hoover
79173        10       state                                     Colorado; CO

[79174 rows x 3 columns]

In [146]:
zillow_regions[zillow_regions['region_type']=='metro']['region']

None
23017                         Zapata, TX; TX
23018    Wisconsin Rapids-Marshfield, WI; WI
23019                     Winnemucca, NV; NV
23020                    Weatherford, OK; OK
23021                 Vineyard Haven, MA; MA
                        ...
51608                            Ada, OK; OK
51610                        Abilene, TX; TX
51611                       Aberdeen, WA; WA
51612                       Aberdeen, SD; SD
78794                          United States
Name: region, Length: 915, dtype: object

In [99]:
list_reg=[list(zillow_regions['region_type'].unique())]
list_reg

[['zip', 'city', 'county', 'neigh', 'state', 'metro']]

In [138]:
#list_reg=[list(zillow_regions['region_type'].unique())]

#for i in range (len(zillow_regions['region_type'].value_counts())):
    
    

new = zillow_regions[zillow_regions['region_type']=='zip']['region'].str.split(";", n = 4, expand = True)

zillow_regions["zipcode"]= new[0]

zillow_regions["state"]= new[1]

zillow_regions["city"]= new[2]

zillow_regions["county"]= new[3]

zillow_regions["country"]= new[4]

In [127]:
new1 = zillow_regions[zillow_regions['region_type']=='city']['region'].str.split(";", n = 3, expand = True)

zillow_regions["city"]= new1[0]

zillow_regions["state"]= new1[1]

zillow_regions["county"]= new1[3]

In [128]:
new1 = zillow_regions[zillow_regions['region_type']=='county']['region'].str.split(";", n = 1, expand = True)

zillow_regions["county"]= new1[0]

zillow_regions["state"]= new1[1]

In [3]:
# new1 = zillow_regions[zillow_regions['region_type']=='county']['metro'].str.split(";", n = 1, expand = True)

# zillow_regions["metro"]= new1[0]

# zillow_regions["state"]= new1[1]

In [2]:
zillow_regions

NameError: name 'zillow_regions' is not defined

In [13]:
zillow_regions[zillow_regions['region_type']=='zip']

      region_id region_type                                             region
None
0         99999         zip     98847; WA; Wenatchee; Chelan County; Peshastin
1         99998         zip                98846; WA; Okanogan County; Pateros
2         99997         zip    98845; WA; Wenatchee; Douglas County; Palisades
3         99996         zip               98844; WA; Okanogan County; Oroville
4         99995         zip       98843; WA; Wenatchee; Douglas County; Orondo
...         ...         ...                                                ...
79165    100004         zip               98852; WA; Okanogan County; Winthrop
79166    100003         zip     98851; WA; Moses Lake; Grant County; Soap Lake
79167    100002         zip  98850; WA; Wenatchee; Douglas County; Rock Island
79168    100001         zip              98849; WA; Okanogan County; Riverside
79169    100000         zip        98848; WA; Moses Lake; Grant County; Quincy

[31158 rows x 3 columns]

In [32]:
zillow_regions[zillow_regions['region_type'] == 'metro'].head(50)

,region_id,region_type,region,zipcode,state,city,county,township,neighborhood
None,,,,,,,,,
23017,753929,metro,"Zapata, TX; TX","Zapata, TX",TX,None,None,None,None
23018,753928,metro,"Wisconsin Rapids-Marshfield, WI; WI","Wisconsin Rapids-Marshfield, WI",WI,None,None,None,None
23019,753927,metro,"Winnemucca, NV; NV","Winnemucca, NV",NV,None,None,None,None
23020,753926,metro,"Weatherford, OK; OK","Weatherford, OK",OK,None,None,None,None
23021,753925,metro,"Vineyard Haven, MA; MA","Vineyard Haven, MA",MA,None,None,None,None
23022,753924,metro,"Urban Honolulu, HI","Urban Honolulu, HI",None,None,None,None,None
23023,753923,metro,"The Dalles, OR; OR","The Dalles, OR",OR,None,None,None,None
23024,753922,metro,"Summit Park, UT; UT","Summit Park, UT",UT,None,None,None,None
23025,753921,metro,"Steamboat Springs, CO; CO","Steamboat Springs, CO",CO,None,None,None,None
23026,753920,metro,"Sonora, CA; CA","Sonora, CA",CA,None,None,None,None
23028,753918,metro,"Shawano, WI; WI","Shawano, WI",WI,None,None,None,None
23029,753917,metro,"Santa Maria-Santa Barbara, CA; CA","Santa Maria-Santa Barbara, CA",CA,None,None,None,None
23030,753916,metro,"Sandpoint, ID; ID","Sandpoint, ID",ID,None,None,None,None
23031,753915,metro,"Salem, OH; OH","Salem, OH",OH,None,None,None,None
23032,753914,metro,"Port Lavaca, TX; TX","Port Lavaca, TX",TX,None,None,None,None
23033,753913,metro,"Port Clinton, OH; OH","Port Clinton, OH",OH,None,None,None,None
23034,753912,metro,"Pinehurst-Southern Pines, NC; NC","Pinehurst-Southern Pines, NC",NC,None,None,None,None
23035,753911,metro,"Ozark, AL; AL","Ozark, AL",AL,None,None,None,None
23036,753910,metro,"Oxford, NC; NC","Oxford, NC",NC,None,None,None,None
23038,753909,metro,"Ottawa, KS; KS","Ottawa, KS",KS,None,None,None,None
23039,753908,metro,"Othello, WA; WA","Othello, WA",WA,None,None,None,None
23040,753906,metro,"North Port-Sarasota-Bradenton, FL","North Port-Sarasota-Bradenton, FL",None,None,None,None,None
23041,753905,metro,"Newport, OR; OR","Newport, OR",OR,None,None,None,None
23042,753904,metro,"Marion, NC; NC","Marion, NC",NC,None,None,None,None
23043,753903,metro,"Marietta, OH; OH","Marietta, OH",OH,None,None,None,None
23044,753902,metro,"Malvern, AR; AR","Malvern, AR",AR,None,None,None,None
23045,753901,metro,"Ludington, MI; MI","Ludington, MI",MI,None,None,None,None
23048,753899,metro,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",None,None,None,None,None
23049,753898,metro,"Logan, WV; WV","Logan, WV",WV,None,None,None,None
23050,753895,metro,"Lafayette-West Lafayette, IN; IN","Lafayette-West Lafayette, IN",IN,None,None,None,None
23051,753894,metro,"Junction City, KS; KS","Junction City, KS",KS,None,None,None,None
23052,753893,metro,"Jefferson, GA; GA","Jefferson, GA",GA,None,None,None,None
23053,753892,metro,"Jackson, OH; OH","Jackson, OH",OH,None,None,None,None
23054,753891,metro,"Ionia, MI; MI","Ionia, MI",MI,None,None,None,None
23055,753890,metro,"Holland, MI; MI","Holland, MI",MI,None,None,None,None
23057,753889,metro,"Hillsdale, MI; MI","Hillsdale, MI",MI,None,None,None,None
23058,753887,metro,"Hermiston-Pendleton, OR; OR","Hermiston-Pendleton, OR",OR,None,None,None,None
23059,753884,metro,"Hailey, ID; ID","Hailey, ID",ID,None,None,None,None
23060,753883,metro,"Greenfield Town, MA; MA","Greenfield Town, MA",MA,None,None,None,None
23061,753881,metro,"Glenwood Springs, CO; CO","Glenwood Springs, CO",CO,None,None,None,None
23062,753880,metro,"Fairfield, IA; IA","Fairfield, IA",IA,None,None,None,None
23064,753879,metro,"Elkins, WV; WV","Elkins, WV",WV,None,None,None,None
23065,753878,metro,"Dayton, TN; TN","Dayton, TN",TN,None,None,None,None
23066,753877,metro,"Cullowhee, NC; NC","Cullowhee, NC",NC,None,None,None,None
23067,753875,metro,"Crestview-Fort Walton Beach-Destin, FL; FL","Crestview-Fort Walton Beach-Destin, FL",FL,None,None,None,None
23068,753874,metro,"Craig, CO; CO","Craig, CO",CO,None,None,None,None
23069,753872,metro,"California-Lexington Park, MD; MD","California-Lexington Park, MD",MD,None,None,None,None
23070,753871,metro,"Breckenridge, CO; CO","Breckenridge, CO",CO,None,None,None,None
23072,753869,metro,"Bloomington, IL; IL","Bloomington, IL",IL,None,None,None,None
23073,753866,metro,"Big Stone Gap, VA; VA","Big Stone Gap, VA",VA,None,None,None,None

### Filtering region column

In [46]:
new = zillow_regions["region"].str.split(";", n = -1, expand = True)
  
# making separate first name column from new data frame
zillow_regions["zipcode"]= new[0]
  
# making separate last name column from new data frame
zillow_regions["state"]= new[1]

zillow_regions["city"]= new[2]

zillow_regions["county"]= new[3]

zillow_regions["neighborhood"]= new[4]
zillow_regions.head()

#test for zip (numbers), state(2 letters), county(contains word county)
#loop throw every row and that region column
#for x in zillow region, x[''] and iterate through list

,region_id,region_type,region,zipcode,state,city,county,township,neighborhood
None,,,,,,,,,
0,99999,zip,98847; WA; Wenatchee; Chelan County; Peshastin,98847,WA,Wenatchee,Chelan County,Peshastin,Peshastin
1,99998,zip,98846; WA; Okanogan County; Pateros,98846,WA,Okanogan County,Pateros,None,None
2,99997,zip,98845; WA; Wenatchee; Douglas County; Palisades,98845,WA,Wenatchee,Douglas County,Palisades,Palisades
3,99996,zip,98844; WA; Okanogan County; Oroville,98844,WA,Okanogan County,Oroville,None,None
4,99995,zip,98843; WA; Wenatchee; Douglas County; Orondo,98843,WA,Wenatchee,Douglas County,Orondo,Orondo
5,99994,zip,98841; WA; Okanogan County; Omak,98841,WA,Okanogan County,Omak,None,None
6,99993,zip,98840; WA; Okanogan County; Okanogan,98840,WA,Okanogan County,Okanogan,None,None
7,99992,zip,98837; WA; Moses Lake; Grant County,98837,WA,Moses Lake,Grant County,None,None
8,99991,zip,98836; WA; Wenatchee; Chelan County,98836,WA,Wenatchee,Chelan County,None,None
9,99990,zip,98834; WA; Okanogan County; Methow,98834,WA,Okanogan County,Methow,None,None
10,9999,city,Carrsville; VA; Virginia Beach-Norfolk-Newport News; Isle of Wight County,Carrsville,VA,Virginia Beach-Norfolk-Newport News,Isle of Wight County,None,None
11,99989,zip,98833; WA; Okanogan County; Mazama,98833,WA,Okanogan County,Mazama,None,None
12,99988,zip,98832; WA; Moses Lake; Grant County; Krupp,98832,WA,Moses Lake,Grant County,Krupp,Krupp
13,99987,zip,98831; WA; Wenatchee; Chelan County; Manson,98831,WA,Wenatchee,Chelan County,Manson,Manson
14,99986,zip,98830; WA; Wenatchee; Douglas County; Mansfield,98830,WA,Wenatchee,Douglas County,Mansfield,Mansfield
15,99985,zip,98829; WA; Okanogan County; Okanogan,98829,WA,Okanogan County,Okanogan,None,None
16,99984,zip,98828; WA; Wenatchee; Chelan County; Malaga,98828,WA,Wenatchee,Chelan County,Malaga,Malaga
17,99983,zip,98827; WA; Okanogan County; Loomis,98827,WA,Okanogan County,Loomis,None,None
18,99982,zip,98826; WA; Wenatchee; Chelan County; Leavenworth,98826,WA,Wenatchee,Chelan County,Leavenworth,Leavenworth
19,99980,zip,98823; WA; Moses Lake; Grant County; Ephrata,98823,WA,Moses Lake,Grant County,Ephrata,Ephrata
20,9998,city,Birchleaf; VA; Big Stone Gap; Dickenson County,Birchleaf,VA,Big Stone Gap,Dickenson County,None,None
21,99979,zip,98822; WA; Wenatchee; Chelan County; Entiat,98822,WA,Wenatchee,Chelan County,Entiat,Entiat
22,99978,zip,98821; WA; Wenatchee; Chelan County; Cashmere,98821,WA,Wenatchee,Chelan County,Cashmere,Cashmere
23,99977,zip,98819; WA; Okanogan County; Omak,98819,WA,Okanogan County,Omak,None,None
24,99976,zip,98817; WA; Wenatchee; Chelan County; Chelan Falls,98817,WA,Wenatchee,Chelan County,Chelan Falls,Chelan Falls
25,99975,zip,98816; WA; Wenatchee; Chelan County; Chelan,98816,WA,Wenatchee,Chelan County,Chelan,Chelan
26,99974,zip,98815; WA; Wenatchee; Chelan County; Cashmere,98815,WA,Wenatchee,Chelan County,Cashmere,Cashmere
27,99973,zip,98814; WA; Okanogan County; Carlton,98814,WA,Okanogan County,Carlton,None,None
28,99972,zip,98813; WA; Wenatchee; Douglas County; Bridgeport,98813,WA,Wenatchee,Douglas County,Bridgeport,Bridgeport
29,99971,zip,98812; WA; Okanogan County; Brewster,98812,WA,Okanogan County,Brewster,None,None
30,99970,zip,98811; WA; Wenatchee; Chelan County; Entiat,98811,WA,Wenatchee,Chelan County,Entiat,Entiat
31,99968,zip,98802; WA; Wenatchee; Douglas County; East Wenatchee Bench,98802,WA,Wenatchee,Douglas County,East Wenatchee Bench,East Wenatchee Bench
32,99967,zip,98801; WA; Wenatchee; Chelan County,98801,WA,Wenatchee,Chelan County,None,None
33,99965,zip,98686,98686,None,None,None,None,None
34,99964,zip,98685,98685,None,None,None,None,None
35,99963,zip,98684; WA; Portland-Vancouver-Hillsboro; Clark County; Vancouver,98684,WA,Portland-Vancouver-Hillsboro,Clark County,Vancouver,Vancouver
36,99962,zip,98683,98683,None,None,None,None,None
37,99961,zip,98682,98682,None,None,None,None,None
38,99960,zip,98675; WA; Portland-Vancouver-Hillsboro; Clark County; Yacolt,98675,WA,Portland-Vancouver-Hillsboro,Clark County,Yacolt,Yacolt
39,99959,zip,98674; WA; Longview; Cowlitz County; Woodland,98674,WA,Longview,Cowlitz County,Woodland,Woodland
40,99958,zip,98673; WA; Klickitat County; Centerville,98673,WA,Klickitat County,Centerville,None,None
41,99957,zip,98672; WA; Klickitat County; White Salmon,98672,WA,Klickitat County,White Salmon,None,None
42,99956,zip,98671; WA; Portland-Vancouver-Hillsboro; Clark County; Washougal,98671,WA,Portland-Vancouver-Hillsboro,Clark County,Washougal,Washougal
43,99955,zip,98670; WA; Klickitat County; Wahkiacus,98670,WA,Klickitat County,Wahkiacus,None,None
44,99951,zip,98665; WA; Portland-Vancouver-Hillsboro; Clark County; Vancouver,98665,WA,Portland-Vancouver-Hillsboro,Clark County,Vancouver,Vancouver
45,99950,zip,98664; WA; Portland-Vancouver-Hillsboro; Clark County; Vancouver,98664,WA,Portland-Vancouver-Hillsboro,Clark County,Vancouver,Vancouver
46,99949,zip,98663; WA; Portland-Vancouver-Hillsboro; Clark County; Vancouver,98663,WA,Portland-Vancouver-Hillsboro,Clark County,Vancouver,Vancouver
47,99948,zip,98662,98662,None,None,None,None,None
48,99947,zip,98661,98661,None,None,None,None,None
49,99946,zip,98660,98660,None,None,None,None,None

In [6]:
# zillow_regions['zipcode'] = 'NAN'

# new = zillow_regions['region'].str.split(';',n = 4, expand=True)
# for i in range(len(zillow_regions)):
#     if new[0][i].isdigit():
#         zillow_regions['zipcode'][i] = new[0][i]


zillow_regions['zipcode'] = 'NAN'
zillow_regions['state'] = 'NAN'
zillow_regions['metro'] = 'NAN'
zillow_regions['city'] = 'NAN'
zillow_regions['county'] = 'NAN'
zillow_regions['neighborhood'] = 'NAN'

for column in range(len(zillow_regions)):
        
    new = zillow_regions['region'].str.split(";", n = -1, expand = True)
#     if new[0][column].isdigit():
#         zillow_regions['zipcode'][column] = new[0][column]
        
#         zillow_regions["zipcode"]= new[0]
    if len(new[0][column]) == 2:
        zillow_regions["state"][column] = new[1][column]
#     if '-' in new:
#         zillow_regions['metro'] = new[2]  
#     else:
#         zillow_regions['city'] = new[2]
#     if 'county' in new:
#         zillow_regions["county"] = new[3]
#     else:
#         zillow_regions['neighborhood'] = new[4]  
        
#print(column)
#if zillow_regions[column].str.split(';').str.len() == 5:
#new = zillow_regions['region'].str.split(';', n = -1, expand=True)

KeyboardInterrupt:

In [8]:
# zillow_regions['zipcode'] = 'NAN'
zillow_regions

,region_id,region_type,region,zipcode,state,metro,city,county,neighborhood
None,,,,,,,,,
0,99999,zip,98847; WA; Wenatchee; Chelan County; Peshastin,NAN,NAN,NAN,NAN,NAN,NAN
1,99998,zip,98846; WA; Okanogan County; Pateros,NAN,NAN,NAN,NAN,NAN,NAN
2,99997,zip,98845; WA; Wenatchee; Douglas County; Palisades,NAN,NAN,NAN,NAN,NAN,NAN
3,99996,zip,98844; WA; Okanogan County; Oroville,NAN,NAN,NAN,NAN,NAN,NAN
4,99995,zip,98843; WA; Wenatchee; Douglas County; Orondo,NAN,NAN,NAN,NAN,NAN,NAN
...,...,...,...,...,...,...,...,...,...
79169,100000,zip,98848; WA; Moses Lake; Grant County; Quincy,NAN,NAN,NAN,NAN,NAN,NAN
79170,10000,city,Bloomington; MD; Garrett County,NAN,NAN,NAN,NAN,NAN,NAN
79171,1000,county,Echols County; GA; Valdosta,NAN,NAN,NAN,NAN,NAN,NAN
79172,100,county,Bibb County; AL; Birmingham-Hoover,NAN,NAN,NAN,NAN,NAN,NAN
79173,10,state,Colorado; CO,NAN,NAN,NAN,NAN,NAN,NAN

In [10]:
new = zillow_regions['region'].str.split(";", n = -1, expand = True)
new[0]

None
0                98847
1                98846
2                98845
3                98844
4                98843
             ...
79169            98848
79170      Bloomington
79171    Echols County
79172      Bibb County
79173         Colorado
Name: 0, Length: 79174, dtype: object

In [39]:
#zillow_regions['region'].str.split(";").str.len()
for column in zillow_regions['region']:
    if zillow_regions[column].str.split(';').str.len() == 5:
        new = zillow_regions["region"].str.split(";", n = -1, expand = True)
        
        if new.isdigit():
            zillow_regions["zipcode"]= new[0]
        if new.len() == 2:
            zillow_regions["state"] = new[1]
        if '-' in new:
            zillow_regions['metro'] = new[2]  
        else:
            zillow_regions['city'] = new[2]
        if 'county' in new:
            zillow_regions["county"] = new[3]
        else:
            zillow_regions['neighborhood'] = new[4]
            
#     elif zillow_regions[column].str.split(';').str.len() == 4:
#         new = zillow_regions["region"].str.split(";", n = 3, expand = True)
        
#zillow_regions[column].str.split(';').str.len() == 4 or 
#zillow_regions[column].str.split(';').str.len() == 3 or 
#zillow_regions[column].str.split(';').str.len() == 2 or zillow_regions[column].str.split(';').str.len() == 1:

KeyError: '98847; WA; Wenatchee; Chelan County; Peshastin'

In [6]:
zillow_regions[zillow_regions['region_type']=='zip']

,region_id,region_type,region,zipcode,state,city,county,country,township
None,,,,,,,,,
0,99999,zip,98847; WA; Wenatchee; Chelan County; Peshastin,98847,WA,Wenatchee,Chelan County,Peshastin,Peshastin
1,99998,zip,98846; WA; Okanogan County; Pateros,98846,WA,Okanogan County,Pateros,None,None
2,99997,zip,98845; WA; Wenatchee; Douglas County; Palisades,98845,WA,Wenatchee,Douglas County,Palisades,Palisades
3,99996,zip,98844; WA; Okanogan County; Oroville,98844,WA,Okanogan County,Oroville,None,None
4,99995,zip,98843; WA; Wenatchee; Douglas County; Orondo,98843,WA,Wenatchee,Douglas County,Orondo,Orondo
...,...,...,...,...,...,...,...,...,...
79165,100004,zip,98852; WA; Okanogan County; Winthrop,98852,WA,Okanogan County,Winthrop,None,None
79166,100003,zip,98851; WA; Moses Lake; Grant County; Soap Lake,98851,WA,Moses Lake,Grant County,Soap Lake,Soap Lake
79167,100002,zip,98850; WA; Wenatchee; Douglas County; Rock Island,98850,WA,Wenatchee,Douglas County,Rock Island,Rock Island
79168,100001,zip,98849; WA; Okanogan County; Riverside,98849,WA,Okanogan County,Riverside,None,None
79169,100000,zip,98848; WA; Moses Lake; Grant County; Quincy,98848,WA,Moses Lake,Grant County,Quincy,Quincy

In [ ]:
zillow_regions['region_type']==''

In [41]:
zillow_regions['zipcode'].value_counts()

Downtown       170
Riverside       40
Franklin        32
Springfield     32
Washington      31
              ...
Wilkinson        1
74438            1
11558            1
29658            1
79411            1
Name: zipcode, Length: 63128, dtype: int64

### Changing datatypes of the columns:

In [28]:
zillow_regions['region_id']=zillow_regions['region_id'].astype('int64')

In [30]:
zillow_regions.dtypes

region_id       int64
region_type    object
region         object
dtype: object