1. Make sure you can get the API from class to work in Azure. Take a screenshot of itworking and add the image to a jupyter notebook.

https://github.com/ytaiwo/Homework/blob/main/week_21/azure_api.png

2. Loop through the API data in python using the /gdp/<year> endpoint for your API. Add the data to a dataframe.

In [31]:
import requests
import pandas as pd
import numpy as np
import re
import json

In [33]:
#from bs4 import BeautifulSoup
import bs4

base_url = "https://flask-app-class-demo-yt.azurewebsites.net/gdp/"
years = range(1960,2021)
gdp_list = []

for year in years:
    
    full_request = base_url + str(year)
    #print(full_request)

    req = requests.get(full_request)

    req.encoding = 'utf-8'

    content = req.text
    
    new_content = bs4.BeautifulSoup(content)
    content_string = new_content.text
    
    mod_string = re.search('{.*}', content_string).group(0)
    json_string = mod_string.replace("'",'"')
    gdp_data = json.loads(json_string)
    
    gdp_list.append([gdp_data['indicator']['id'], gdp_data['indicator']['value'], gdp_data['country']['id'],
                    gdp_data['country']['value'], gdp_data['countryiso3code'],gdp_data['date'],gdp_data['value'],
                    gdp_data['unit'],gdp_data['obs_status'],gdp_data['decimal']])
    
    
#create dataframe
gdp_df = pd.DataFrame(gdp_list,columns=['indicator_id','indicator_value','country_id','country_value','countryiso3code',
                                        'date', 'value', 'unit', 'obs_status', 'decimal'])
gdp_df

,indicator_id,indicator_value,country_id,country_value,countryiso3code,date,value,unit,obs_status,decimal
0,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,1960,543300000000,,,0
1,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,1961,563300000000,,,0
2,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,1962,605100000000,,,0
3,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,1963,638600000000,,,0
4,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,1964,685800000000,,,0
...,...,...,...,...,...,...,...,...,...,...
56,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,2016,18745075687000,,,0
57,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,2017,19542979183000,,,0
58,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,2018,20611860934000,,,0
59,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,2019,21433224697000,,,0
60,NY.GDP.MKTP.CD,GDP (current US$),US,United States,USA,2020,20936600000000,,,0