In [1]:
import pandas as pd

belize_path = "belize_airbnb_listings.csv"
belize_df = pd.read_csv(belize_path)

In [2]:
belize_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,36666,Mo's Cozy Casa w/ veranda & access to dock,157752,Monique,Belize,Belize Islands,17.74786,-88.02398,Entire home/apt,141,3,250,2/23/2021,2.00,5,225
1,36690,Mo's Cozy Cabana w/ comfy veranda & access to ...,157752,Monique,Belize,Belize Islands,17.74832,-88.02474,Entire home/apt,71,3,316,2/19/2021,2.46,5,164
2,108932,Purple House eco solar w/ ocean & wildlife views,563377,Michael,Belize,Belize Islands,17.73221,-88.03824,Entire home/apt,191,2,30,3/14/2020,0.78,1,364
3,110483,Michelo's fuchsia suite,567809,Michel,Stann Creek,Stann Creek Mainland,16.52114,-88.36926,Hotel room,121,1,27,2/24/2020,0.29,3,331
4,120115,Seaside Villas Second Floor Unit #4,604999,Bobbi,Belize,Belize Islands,17.74166,-88.02395,Entire home/apt,343,1,30,3/18/2020,0.64,22,203

In [4]:
neighbourhood = belize_df.groupby("neighbourhood")

neighbourhood_info = pd.DataFrame({"Maximum Price":neighbourhood["price"].max(),
                                   "Average Price":neighbourhood["price"].mean()})

neighbourhood_info

                      Maximum Price  Average Price
neighbourhood
Belize Islands                 6045     399.442824
Belize Mainland                3808     288.273063
Cayo                           5430     205.847525
Corozal                         401     156.553846
Orange Walk                     403     122.035714
Stann Creek Islands            5037    1136.166667
Stann Creek Mainland          11788     456.994690
Toledo Mainland                1121     222.978723